### ISSUE TITLE
Use PyPI API token

### ISSUE THREAD

**Issue by alexpovel** [StefanUlbrich/design-by-contract#10]
It's [recommended](https://pypi.org/help/#apitoken) to use API tokens when authenticating (pushing) to PyPI:

> API tokens provide an alternative way (instead of username and password) to authenticate when uploading packages to PyPI.
>
> You can create a token for an entire PyPI account, in which case, the token will work for all projects associated with that account. Alternatively, you can limit a token's scope to a specific project.
>
> We strongly recommend you authenticate with an API token where possible.

~~Tokens are also mandatory when using 2FA on PyPI.~~ Scratch that, [they aren't mandatory (*yet*)](https://pypi.org/help/#twofa):

> This only affects logging in via a web browser, and not (yet) package uploads. 

So this:

https://github.com/StefanUlbrich/design-by-contract/blob/67f6ea9b6b9e3f3958068753da33a7b03f6e84e7/.github/workflows/release.yaml#L25-L27

Could read, [for example](https://github.com/alexpovel/betterletter/blob/eee633f29a5c1ecd2e6d5efa22d8cd361c3ffe78/.github/workflows/publish.yml#L20-L24):

```yaml
      - name: Publish package
        uses: pypa/gh-action-pypi-publish@v1.5.0
        with:
          user: __token__
          password: ${{ secrets.PYPI_API_TOKEN }}
```

I could create a PR but you would have to figure out the API token stuff anyway so it'd be hard to test for me.
